'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Address
    Public Property AddressID As Integer
    Public Property Address1 As String
    Public Property Address2 As String
    Public Property City As String
    Public Property StateID As Nullable(Of Integer)
    Public Property State As String
    Public Property PostalCode As String
    Public Property CountryID As Nullable(Of Integer)
    Public Property Archived As Boolean
    Public Property DateCreated As Date
    Public Property CreatedBy As Integer
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property FullAddress As String

    Public Overridable Property MetaCountry As MetaCountry
    Public Overridable Property MetaState As MetaState
    Public Overridable Property AppSettings As ICollection(Of AppSetting) = New HashSet(Of AppSetting)
    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)
    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)
    Public Overridable Property CustomerContacts As ICollection(Of CustomerContact) = New HashSet(Of CustomerContact)

End Class
