'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Attachment
    Public Property AttachmentID As Integer
    Public Property ObjectID As Nullable(Of Integer)
    Public Property KeyID As Nullable(Of Integer)
    Public Property AttachmentTypeID As Nullable(Of Integer)
    Public Property FileName As String
    Public Property OriginalFileName As String
    Public Property FilePath As String
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Integer)

    Public Overridable Property MetaTypeItem As MetaTypeItem
    Public Overridable Property User As User

End Class
