'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class AuditLog
    Public Property LogID As Integer
    Public Property ObjectID As Nullable(Of Integer)
    Public Property KeyID As Nullable(Of Integer)
    Public Property AttributeID As Nullable(Of Integer)
    Public Property AttributeKeyID As Nullable(Of Integer)
    Public Property AuditLogText As String
    Public Property EffectiveDate As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateCreated As Nullable(Of Date)

    Public Overridable Property MetaAuditLogAttribute As MetaAuditLogAttribute
    Public Overridable Property User As User

End Class
