'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Category
    Public Property CategoryID As Integer
    Public Property CategoryName As String
    Public Property Description As String
    Public Property ParentID As Nullable(Of Integer)
    Public Property Archived As Nullable(Of Boolean)
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property SortOrder As Nullable(Of Integer)

End Class
