'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class CMSMergeField
    Public Property MergeFieldID As Integer
    Public Property MergeField As String

    Public Overridable Property CMSCategories As ICollection(Of CMSCategory) = New HashSet(Of CMSCategory)

End Class
