'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Customer
    Public Property CustomerID As Integer
    Public Property CustomerName As String
    Public Property Notes As String
    Public Property NotesText As String
    Public Property AddressID As Nullable(Of Integer)
    Public Property Phone As String
    Public Property Fax As String
    Public Property Website As String
    Public Property StatusID As Nullable(Of Integer)
    Public Property Archived As Boolean
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)

    Public Overridable Property Address As Address
    Public Overridable Property Notes1 As ICollection(Of Note) = New HashSet(Of Note)
    Public Overridable Property Documents As ICollection(Of Document) = New HashSet(Of Document)
    Public Overridable Property CustomerContacts As ICollection(Of CustomerContact) = New HashSet(Of CustomerContact)

End Class
