'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class EmailLog
    Public Property EmailID As Integer
    Public Property ToAddress As String
    Public Property FromAddress As String
    Public Property Subject As String
    Public Property Body As String
    Public Property Sent As Boolean
    Public Property DateCreated As Date
    Public Property CreatedBy As Nullable(Of Integer)

End Class
