'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class ManagedTypeAssociation
    Public Property TypeID As Integer
    Public Property ObjectID As Integer
    Public Property KeyID As Integer

    Public Overridable Property ManagedType As ManagedType
    Public Overridable Property MetaObject As MetaObject

End Class
