'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class ManagedType
    Public Property TypeID As Integer
    Public Property TypeName As String
    Public Property FriendlyName As String
    Public Property IsHierarchy As Boolean

    Public Overridable Property ManagedTypeAssociations As ICollection(Of ManagedTypeAssociation) = New HashSet(Of ManagedTypeAssociation)
    Public Overridable Property ManagedTypeItems As ICollection(Of ManagedTypeItem) = New HashSet(Of ManagedTypeItem)

End Class
