'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaModule
    Public Property ModuleID As Integer
    Public Property ModuleName As String
    Public Property ParentID As Integer

    Public Overridable Property MetaForms As ICollection(Of MetaForm) = New HashSet(Of MetaForm)
    Public Overridable Property MetaFunctions As ICollection(Of MetaFunction) = New HashSet(Of MetaFunction)

End Class
