'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaMenu
    Public Property MenuID As Integer
    Public Property ParentID As Nullable(Of Integer)
    Public Property Title As String
    Public Property NavigateUrl As String
    Public Property FormID As Nullable(Of Integer)
    Public Property IsInternalOnly As Boolean
    Public Property SortOrder As Nullable(Of Integer)

    Public Overridable Property MetaForm As MetaForm
    Public Overridable Property MetaMenu1 As ICollection(Of MetaMenu) = New HashSet(Of MetaMenu)
    Public Overridable Property MetaMenu2 As MetaMenu

End Class
