'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaFunction
    Public Property FunctionID As Integer
    Public Property FunctionName As String
    Public Property ModuleID As Nullable(Of Integer)
    Public Property ViewOnly As Boolean
    Public Property Archived As Boolean
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)

    Public Overridable Property MetaModule As MetaModule
    Public Overridable Property MetaForms As ICollection(Of MetaForm) = New HashSet(Of MetaForm)
    Public Overridable Property UserRoles As ICollection(Of UserRole) = New HashSet(Of UserRole)

End Class
