'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaAuditLogAttribute
    Public Property AttributeID As Integer
    Public Property AttributeName As String
    Public Property InsertLogText As String
    Public Property UpdateLogText As String

    Public Overridable Property AuditLogs As ICollection(Of AuditLog) = New HashSet(Of AuditLog)

End Class
