'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaToolTip
    Public Property ToolTipID As Integer
    Public Property ToolTipName As String
    Public Property ToolTipDesc As String
    Public Property DateCreated As Nullable(Of Date)

End Class
