'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaState
    Public Property StateID As Integer
    Public Property CountryID As Nullable(Of Integer)
    Public Property StateName As String
    Public Property StateCode As String
    Public Property IsTerritory As Boolean

    Public Overridable Property Addresses As ICollection(Of Address) = New HashSet(Of Address)
    Public Overridable Property MetaCountry As MetaCountry

End Class
