'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaForm
    Public Property FormID As Integer
    Public Property FormName As String
    Public Property FormPath As String
    Public Property CanBeFavorite As Boolean
    Public Property ModuleID As Nullable(Of Integer)
    Public Property DateCreated As Date

    Public Overridable Property MetaModule As MetaModule
    Public Overridable Property MetaMenus As ICollection(Of MetaMenu) = New HashSet(Of MetaMenu)
    Public Overridable Property UserSearchFilters As ICollection(Of UserSearchFilter) = New HashSet(Of UserSearchFilter)
    Public Overridable Property MetaFunctions As ICollection(Of MetaFunction) = New HashSet(Of MetaFunction)
    Public Overridable Property UserFavorites As ICollection(Of UserFavorite) = New HashSet(Of UserFavorite)

End Class
