'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaCountry
    Public Property CountryID As Integer
    Public Property CountryName As String
    Public Property CountryCode As String
    Public Property Include As Boolean
    Public Property SortOrder As Integer

    Public Overridable Property Addresses As ICollection(Of Address) = New HashSet(Of Address)
    Public Overridable Property MetaStates As ICollection(Of MetaState) = New HashSet(Of MetaState)

End Class
