'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaObject
    Public Property ObjectID As Integer
    Public Property ObjectName As String

    Public Overridable Property ManagedTypeAssociations As ICollection(Of ManagedTypeAssociation) = New HashSet(Of ManagedTypeAssociation)

End Class
