'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class MetaTypeItem
    Public Property ItemID As Integer
    Public Property TypeID As Nullable(Of Integer)
    Public Property ItemName As String

    Public Overridable Property Attachments As ICollection(Of Attachment) = New HashSet(Of Attachment)
    Public Overridable Property CMSCategories As ICollection(Of CMSCategory) = New HashSet(Of CMSCategory)
    Public Overridable Property CMSCategories1 As ICollection(Of CMSCategory) = New HashSet(Of CMSCategory)
    Public Overridable Property MetaType As MetaType
    Public Overridable Property Notes As ICollection(Of Note) = New HashSet(Of Note)
    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
