'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class Order
    Public Property OrderID As Integer
    Public Property CustomerID As Nullable(Of Integer)
    Public Property DateOrdered As Nullable(Of Date)
    Public Property PaymentTypeID As Nullable(Of Integer)
    Public Property BillingAddress1 As String
    Public Property BillingAddress2 As String
    Public Property BillingCity As String
    Public Property BillingState As String
    Public Property BillingZip As String
    Public Property ShippingAddress1 As String
    Public Property ShippingAddress2 As String
    Public Property ShippingCity As String
    Public Property ShippingState As String
    Public Property ShippingZip As String
    Public Property ContactPhone As String
    Public Property Tax As Nullable(Of Double)
    Public Property Shipping As Nullable(Of Double)
    Public Property OrderTotal As Nullable(Of Double)
    Public Property Archived As Nullable(Of Boolean)
    Public Property DateCreated As Nullable(Of Date)
    Public Property CreatedBy As Nullable(Of Integer)
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property OrderStatusID As Nullable(Of Integer)
    Public Property DateShipped As Nullable(Of Date)
    Public Property TrackingNumber As String

End Class
