'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class UserRole
    Public Property UserRoleID As Integer
    Public Property UserRoleName As String
    Public Property UserRoleDesc As String
    Public Property Archived As Boolean
    Public Property DateCreated As Date
    Public Property CreatedBy As Integer
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)

    Public Overridable Property MetaFunctions As ICollection(Of MetaFunction) = New HashSet(Of MetaFunction)
    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
