'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class User
    Public Property UserID As Integer
    Public Property Firstname As String
    Public Property Lastname As String
    Public Property Fullname As String
    Public Property Username As String
    Public Property UserKey As Byte()
    Public Property Password As Byte()
    Public Property JobTitleID As Nullable(Of Integer)
    Public Property AddressID As Nullable(Of Integer)
    Public Property Email As String
    Public Property WorkPhone As String
    Public Property WorkPhoneExt As String
    Public Property MobilePhone As String
    Public Property HomePhone As String
    Public Property Notes As String
    Public Property NotesText As String
    Public Property StatusID As Integer
    Public Property ResetKey As Byte()
    Public Property DateResetKeyIssued As Nullable(Of Date)
    Public Property Archived As Boolean
    Public Property DateCreated As Date
    Public Property CreatedBy As Integer
    Public Property DateModified As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)

    Public Overridable Property Address As Address
    Public Overridable Property Attachments As ICollection(Of Attachment) = New HashSet(Of Attachment)
    Public Overridable Property AuditLogs As ICollection(Of AuditLog) = New HashSet(Of AuditLog)
    Public Overridable Property MetaTypeItem As MetaTypeItem
    Public Overridable Property UserFavorites As ICollection(Of UserFavorite) = New HashSet(Of UserFavorite)
    Public Overridable Property UserJobTitle As UserJobTitle
    Public Overridable Property UserLoginLogs As ICollection(Of UserLoginLog) = New HashSet(Of UserLoginLog)
    Public Overridable Property UserSearchFilters As ICollection(Of UserSearchFilter) = New HashSet(Of UserSearchFilter)
    Public Overridable Property UserRoles As ICollection(Of UserRole) = New HashSet(Of UserRole)
    Public Overridable Property Documents As ICollection(Of Document) = New HashSet(Of Document)
    Public Overridable Property Documents1 As ICollection(Of Document) = New HashSet(Of Document)

End Class
