'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class UserSearchFilter
    Public Property FilterID As Integer
    Public Property UserID As Integer
    Public Property FormID As Integer
    Public Property SearchName As String
    Public Property SearchValue As String
    Public Property DateCreated As Date

    Public Overridable Property MetaForm As MetaForm
    Public Overridable Property User As User

End Class
