'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

<Serializable()>
Partial Public Class UserLoginLog
    Public Property LogID As Integer
    Public Property UserID As Nullable(Of Integer)
    Public Property DateCreated As Nullable(Of Date)

    Public Overridable Property User As User

End Class
